use crate::{config::RouterConfig, error::RouterError};
use crate::daemon::process::ManagedProcess;
use std::path::PathBuf;
use tracing::info;

/// Manages the `dnsmasq` process (DHCP + DNS server).
pub struct DnsmasqManager {
    process: Option<ManagedProcess>,
    config_path: PathBuf,
}

impl DnsmasqManager {
    pub fn new() -> Self {
        Self { process: None, config_path: PathBuf::from("/tmp/pi-router-dnsmasq.conf") }
    }

    /// Generate the dnsmasq config file and start the process.
    pub fn start(&mut self, cfg: &RouterConfig) -> Result<(), RouterError> {
        self.config_path = write_dnsmasq_conf(cfg)?;
        let proc = ManagedProcess::spawn(
            "dnsmasq",
            "dnsmasq",
            vec![
                "--no-daemon".into(),
                "--conf-file".into(),
                self.config_path.to_string_lossy().to_string(),
            ],
        )?;
        self.process = Some(proc);
        Ok(())
    }

    pub fn stop(&mut self) {
        if let Some(p) = &mut self.process {
            p.stop();
        }
        self.process = None;
    }

    pub fn is_alive(&mut self) -> bool {
        self.process.as_mut().map(|p| p.is_alive()).unwrap_or(false)
    }

    pub fn restart_count(&self) -> u32 {
        self.process.as_ref().map(|p| p.restart_count).unwrap_or(0)
    }

    pub fn restart(&mut self) -> Result<(), RouterError> {
        if let Some(p) = &mut self.process {
            p.restart()
        } else {
            Err(RouterError::Daemon("dnsmasq process not started".into()))
        }
    }
}

// ─── Config generation ────────────────────────────────────────────────────────

/// Write a dnsmasq.conf from the router configuration.
pub fn write_dnsmasq_conf(cfg: &RouterConfig) -> Result<PathBuf, RouterError> {
    let dhcp = &cfg.dhcp;
    let ap   = &cfg.ap;
    let path = PathBuf::from("/tmp/pi-router-dnsmasq.conf");

    let dns_list = dhcp.dns_servers.join(",");
    let pid_file = "/tmp/pi-router-dnsmasq.pid";

    let content = format!(
        "# Generated by pi-router — do not edit manually\n\
         interface={iface}\n\
         listen-address={ap_ip}\n\
         bind-interfaces\n\
         server={dns}\n\
         domain-needed\n\
         bogus-priv\n\
         dhcp-range={range_start},{range_end},{lease}\n\
         dhcp-option=3,{ap_ip}\n\
         dhcp-option=6,{dns}\n\
         dhcp-leasefile=/tmp/pi-router-dnsmasq.leases\n\
         pid-file={pid_file}\n\
         log-dhcp\n",
        iface       = ap.interface,
        ap_ip       = dhcp.ap_ip,
        dns         = dns_list,
        range_start = dhcp.range_start,
        range_end   = dhcp.range_end,
        lease       = dhcp.lease_time,
        pid_file    = pid_file,
    );

    info!(path = %path.display(), "Writing dnsmasq config");
    std::fs::write(&path, content)?;
    Ok(path)
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;

    fn sample_config() -> RouterConfig {
        RouterConfig {
            wan: WanConfig { interface: "eth0".into() },
            ap: ApConfig {
                interface: "wlan1".into(),
                ssid:      "TestNet".into(),
                password:  "testpass123".into(),
                channel:   6,
                hw_mode:   "g".into(),
                country_code: "VN".into(),
                ieee80211n: true,
                wmm_enabled: true,
            },
            dhcp: DhcpConfig {
                ap_ip:       "192.168.100.1".into(),
                netmask:     "255.255.255.0".into(),
                prefix_len:  24,
                range_start: "192.168.100.10".into(),
                range_end:   "192.168.100.200".into(),
                lease_time:  "12h".into(),
                dns_servers: vec!["8.8.8.8".into(), "1.1.1.1".into()],
            },
            monitor: MonitorConfig { check_interval_secs: 5, max_restart_attempts: 3 },
            approval: crate::config::ApprovalConfig::default(),
            log_level: "info".into(),
        }
    }

    #[test]
    fn generates_dnsmasq_conf() {
        let cfg = sample_config();
        let path = write_dnsmasq_conf(&cfg).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("interface=wlan1"));
        assert!(content.contains("listen-address=192.168.100.1"));
        assert!(content.contains("dhcp-range=192.168.100.10,192.168.100.200,12h"));
        assert!(content.contains("server=8.8.8.8,1.1.1.1"));
        let _ = std::fs::remove_file(path);
    }
}
