use crate::{config::RouterConfig, error::RouterError};
use crate::daemon::process::ManagedProcess;
use std::path::PathBuf;
use tracing::info;

/// Manages the `hostapd` process (WiFi Access Point daemon).
pub struct HostapdManager {
    process: Option<ManagedProcess>,
    config_path: PathBuf,
}

impl HostapdManager {
    pub fn new() -> Self {
        Self { process: None, config_path: PathBuf::from("/tmp/pi-router-hostapd.conf") }
    }

    /// Generate the hostapd config file and start the process.
    pub fn start(&mut self, cfg: &RouterConfig) -> Result<(), RouterError> {
        self.config_path = write_hostapd_conf(cfg)?;
        let proc = ManagedProcess::spawn(
            "hostapd",
            "hostapd",
            vec![self.config_path.to_string_lossy().to_string()],
        )?;
        self.process = Some(proc);
        Ok(())
    }

    pub fn stop(&mut self) {
        if let Some(p) = &mut self.process {
            p.stop();
        }
        self.process = None;
    }

    pub fn is_alive(&mut self) -> bool {
        self.process.as_mut().map(|p| p.is_alive()).unwrap_or(false)
    }

    pub fn restart_count(&self) -> u32 {
        self.process.as_ref().map(|p| p.restart_count).unwrap_or(0)
    }

    pub fn restart(&mut self) -> Result<(), RouterError> {
        if let Some(p) = &mut self.process {
            p.restart()
        } else {
            Err(RouterError::Daemon("hostapd process not started".into()))
        }
    }
}

// ─── Config generation ───────────────────────────────────────────────────────

/// Write a hostapd.conf from the router configuration.
/// Returns the path to the written file.
pub fn write_hostapd_conf(cfg: &RouterConfig) -> Result<PathBuf, RouterError> {
    let ap = &cfg.ap;
    let path = PathBuf::from("/tmp/pi-router-hostapd.conf");

    let wmm = if ap.wmm_enabled { 1 } else { 0 };
    let n   = if ap.ieee80211n { 1 } else { 0 };
    let ac  = if ap.ieee80211ac { 1 } else { 0 };
    let ax  = if ap.ieee80211ax { 1 } else { 0 };
    let hidden = if ap.ignore_broadcast_ssid { 1 } else { 0 };

    let wpa_block = if ap.password_enabled {
        format!(
            "wpa=2\nwpa_key_mgmt=WPA-PSK\nwpa_passphrase={}\nrsn_pairwise=CCMP\n",
            ap.password
        )
    } else {
        // Open network — no WPA lines
        String::new()
    };

    let content = format!(
        "# Generated by pi-router — do not edit manually\n\
         interface={iface}\n\
         driver=nl80211\n\
         ssid={ssid}\n\
         hw_mode={hw_mode}\n\
         channel={channel}\n\
         country_code={country}\n\
         ieee80211n={n}\n\
         ieee80211ac={ac}\n\
         ieee80211ax={ax}\n\
         wmm_enabled={wmm}\n\
         macaddr_acl=0\n\
         auth_algs=1\n\
         ignore_broadcast_ssid={hidden}\n\
         {wpa}",
        iface    = ap.interface,
        ssid     = ap.ssid,
        hw_mode  = ap.hw_mode,
        channel  = ap.channel,
        country  = ap.country_code,
        n        = n,
        ac       = ac,
        ax       = ax,
        wmm      = wmm,
        hidden   = hidden,
        wpa      = wpa_block,
    );

    info!(path = %path.display(), "Writing hostapd config");
    std::fs::write(&path, content)?;
    Ok(path)
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::*;

    fn sample_config() -> RouterConfig {
        RouterConfig {
            wan: WanConfig { interface: "eth0".into() },
            ap: ApConfig {
                interface: "wlan1".into(),
                ssid:      "TestNet".into(),
                password:  "testpass123".into(),
                channel:   6,
                hw_mode:   "g".into(),
                country_code: "VN".into(),
                ieee80211n: true,
                wmm_enabled: true,
            },
            dhcp: DhcpConfig {
                ap_ip:       "192.168.100.1".into(),
                netmask:     "255.255.255.0".into(),
                prefix_len:  24,
                range_start: "192.168.100.10".into(),
                range_end:   "192.168.100.200".into(),
                lease_time:  "12h".into(),
                dns_servers: vec!["8.8.8.8".into()],
            },
            monitor: MonitorConfig { check_interval_secs: 5, max_restart_attempts: 3 },
            approval: crate::config::ApprovalConfig::default(),
            log_level: "info".into(),
        }
    }

    #[test]
    fn generates_hostapd_conf() {
        let cfg = sample_config();
        let path = write_hostapd_conf(&cfg).unwrap();
        let content = std::fs::read_to_string(&path).unwrap();
        assert!(content.contains("ssid=TestNet"));
        assert!(content.contains("interface=wlan1"));
        assert!(content.contains("wpa_passphrase=testpass123"));
        assert!(content.contains("channel=6"));
        let _ = std::fs::remove_file(path);
    }
}
